Repository b-gaebalja/b-log-frontend, pull requests merged in 2024-10, with the labels that each got.

#6 [#2] 게시글 도메인 이름, 게시글 등록 요청 경로 변경
  src/api/config.js
  src/api/postApi.js
  src/api/userApi.js
  src/components/board/AddComponent.jsx
  src/components/board/ReadComponent.jsx
  src/components/board/ScrapComponent.jsx
  src/components/board/list/ListBasicComponent.jsx
  src/components/board/list/ListMyComponent.jsx
  src/components/menus/common/LeftSideMenu.jsx
  src/components/menus/member/CustomMenu.jsx
  src/components/menus/share/ShareMenu.jsx
  src/components/post/AddByEditorComponent.jsx
  src/components/post/AddComponent.jsx
  src/components/post/CopyUrlComponent.jsx
  src/components/post/ModifyByEditorComponent.jsx
  src/components/post/ReadComponent.jsx
  src/components/post/ScrapComponent.jsx
  src/components/post/SnsShareComponent2.jsx
  src/components/post/ViewerComponent.jsx
  src/components/post/list/ListBasicComponent.jsx
  src/components/post/list/ListMyComponent.jsx
  src/pages/board/AddByEditorPage.jsx
  src/pages/board/AddPage.jsx
  src/pages/board/ReadPage.jsx
  src/pages/board/ScrapPage.jsx
  src/pages/board/ViewerPage.jsx
  src/pages/board/list/ListBasicPage.jsx
  src/pages/board/list/ListMyPage.jsx
  src/pages/post/AddByEditorPage.jsx
  src/pages/post/AddPage.jsx
  src/pages/post/IndexPage.jsx
  src/pages/post/ModifyByEditorPage.jsx
  src/pages/post/ReadPage.jsx
  src/pages/post/ScrapPage.jsx
  src/pages/post/ViewerPage.jsx
  src/pages/post/list/ListBasicPage.jsx
  src/pages/post/list/ListMyPage.jsx
  src/router/boardRouter.jsx
  src/router/postRouter.jsx
  src/router/root.jsx
Labels: enhancement, style

#8 [#7] 게시글 등록 시 로그인 회원 이메일 주소 연결
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#10 [#9] 게시글 등록 성공 시 모달 창 적용
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#16 [#15] 게시글 작성 시 이미지 저장 기능 추가
  src/api/config.js
  src/api/imageApi.js
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#18 [#17] 게시글 임시저장 기능 추가
  src/api/postApi.js
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#20 [#19] 게시글 등록 시 resultModal에 전송되는 open property 추가
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#24 [#22] 게시글 작성 시 인증 기능 추가
  src/components/post/AddByEditorComponent.jsx
Labels: enhancement

#25 [#23] 게시글 조회 기능 추가
  src/api/postApi.js
  src/components/post/ViewerComponent.jsx
Labels: enhancement

#36 Merge(dev -> main)
  src/api/config.js
Labels: deployment

#38 [#37]게시글 목록 조회 기능 추가
  src/api/postApi.js
  src/components/main/MainComponent.jsx
  src/components/post/list/ListBasicComponent.jsx
  src/components/post/list/ListMyComponent.jsx
  src/pages/post/list/ListMyPage.jsx
Labels: enhancement

#39 Merge(dev -> main)
  src/api/postApi.js
  src/components/main/MainComponent.jsx
  src/components/post/list/ListBasicComponent.jsx
  src/components/post/list/ListMyComponent.jsx
  src/pages/post/list/ListMyPage.jsx
Labels: deployment

#45 [#43] 게시글 수정 기능 추가
  src/api/postApi.js
  src/components/post/AddByEditorComponent.jsx
  src/components/post/ModifyByEditorComponent.jsx
  src/components/post/ViewerComponent.jsx
Labels: enhancement

#46 Merge(dev -> main)
  src/api/postApi.js
  src/components/post/AddByEditorComponent.jsx
  src/components/post/ModifyByEditorComponent.jsx
  src/components/post/ViewerComponent.jsx
  src/util/jwtUtil.jsx
Labels: deployment

#52 [#51] API 요청에 JwtAxios 적용
  src/api/postApi.js
Labels: enhancement

#53 Merge(dev -> main)
  src/api/postApi.js
  src/components/post/ViewerComponent.jsx
  src/components/post/list/ListBasicComponent.jsx
  src/pages/post/ScrapPage2.jsx
  src/pages/post/ViewerPage.jsx
  src/router/postRouter.jsx
Labels: deployment

#55 Merge(dev -> main)
  src/components/post/PostDetailComponent.jsx
  src/components/post/ScrapedListComponent2.jsx
Labels: deployment

#58 Merge(dev -> main)
  package-lock.json
  package.json
  src/components/post/ShareComponent.jsx
Labels: deployment

#61 Merge(dev -> main)
  src/api/config.js
  src/api/postApi.js
Labels: deployment

#63 [#62] 메인 페이지가 list를 거치지 않고 루트로 라우팅되도록 수정
  src/api/postApi.js
  src/router/root.jsx
Labels: configuration

#64 Merge(dev -> main)
  src/api/postApi.js
  src/router/root.jsx
Labels: deployment

#69 [#68] 세부적인 변경사항들 적용
  src/components/menus/common/LeftSideMenu.jsx
  src/components/menus/share/ShareMyMenu.jsx
Labels: enhancement

#70 Merge(dev->main)
  src/api/commentApi.jsx
  src/api/config.js
  src/components/comment/CommentComponent.jsx
  src/components/menus/common/LeftSideMenu.jsx
  src/components/menus/share/ShareMyMenu.jsx
  src/components/post/ReadComponent.jsx
Labels: deployment

#73 [#51] API 요청에 JwtAxios 적용
  src/api/imageApi.js
Labels: enhancement

#75 Merge(dev->main)
  src/api/imageApi.js
  src/components/post/ReadComponent.jsx
  src/components/post/ViewerComponent.jsx
Labels: deployment

#90 [#87] 게시글 삭제 기능 추가
  src/api/postApi.js
  src/components/comment/CommentComponent.jsx
  src/components/menus/share/ShareMyMenu.jsx
  src/components/post/ViewerComponent.jsx
Labels: enhancement

#97 Merge(dev->merge)
  src/api/postApi.js
  src/components/post/ListBookmarkedComponent.jsx
  src/components/post/ViewerComponent.jsx
  src/components/post/list/ListBasicComponent.jsx
Labels: deployment

#99 Merge(dev->merge)
  src/components/post/ViewerComponent.jsx
Labels: deployment

#107 Merge(dev->merge)
  src/components/comment/CommentComponent.jsx
Labels: deployment
